
SRC		= ft_putchar.c ft_swap.c ft_putstr.c ft_strlen.c ft_strcmp.c
PSRC	= srcs/
SRCS	= ${addprefix ${PSRC}, ${SRC}} 

HEADER	= includes/

OBJS	= ${SRCS:.c=.o}

NAME	= libft.a

CC		= gcc

RM		= rm -f

CFLAGS	= -Wall -Wextra -Werror

.c.o:
	${CC} ${CFLAGS} -I ${HEADER} -c $< -o ${<:.c=.o}

${NAME}:	${OBJS}
		ar rc ${NAME} ${OBJS}

all:	${NAME}

clean:
		${RM} ${OBJS}

fclean:	clean
		${RM} ${NAME}

re:		fclean all

.PHONY:	all clean fclean re
